### ISSUE TITLE
读取个excel再输出为sqlite3时，excel的第一行读取不出来，输出失败。

### ISSUE THREAD

**Issue by petra1218** [JacksonWuxs/DaPy#11]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by JacksonWuxs** [comment]
感谢您汇报的bug，该bug已被最新版的DaPy（1.11.1）给修复，请您更新到最新版本。
