### ISSUE TITLE
UnicodeDecodeError: 'gbk' codec can't decode byte 0xae in position 48: illegal multibyte sequence

### ISSUE THREAD

**Issue by ice-tong** [JacksonWuxs/DaPy#12]
DaPy.read() 添加enconding编码参数，带中文的csv读不了。

**Comment by JacksonWuxs** [comment]
你需要明确一下你的中文csv的编码格式哦~
按照你的报错信息，应该你的文本编码格式是utf-8，你可以把函数改成：DaPy.read('文件地址.csv', encoding='utf-8')

**Comment by ice-tong** [comment]
就是说DaPy.read()这个函数没有encoding这个参数

**Comment by JacksonWuxs** [comment]
如果你是Python3环境下的话是有这个参数的，可能是readme还没有更新。但是python2的情况下，这个参数不会被启用。

**Comment by ice-tong** [comment]
的确有，我搞错了，谢谢回复。
