### ISSUE TITLE
AssertionError:Sn is not a title in current dataset

### ISSUE THREAD

**Issue by zyuerugou** [JacksonWuxs/DaPy#14]
用DaPy.read()读入一个xlsx文件，其中有三个sheet，前两个sheet有数据，最后一个Sheet3是创建文件的时候默认的，里面没有数据。

读入之后，调用DaPy.core.DataSet.DataSet.info，有数据的两个sheet输出正常结果，但是Sheet3报错，报错提示如标题。

另：建议将guide book的链接放到项目的readme.md
2333

**Comment by JacksonWuxs** [comment]
好滴好滴，感谢建议以及报错信息！
最近有点忙，一直没有release最新版本~
