### ISSUE TITLE
Code formatting in README

### ISSUE THREAD

**Issue by Dmitrii-I** [JacksonWuxs/DaPy#2]
The code examples in README would be best formatted as code and not as plain text, to stand out.

I also believe you need a README.rst not README.md for pypi.

**Comment by JacksonWuxs** [comment]
Of couse README.rst  is neccessary! At the begining, I thought README.md has replaced README.rst in Github. So you mean that, I should upload the README.rst at the same time?
And to the issues about example, should I write my examples in README? Anyway, I will update a new README in next week.
Thanks for your suggestion!

**Comment by Dmitrii-I** [comment]
@JacksonWuxs 

What I meant by formatting the code as code is to to use 4 spaces in front of code, like so:

    import datapy

 or wrap the code with back-ticks like so: `import datapy`. This is just my personal preference though.

Github renders both README.md and README.rst fine. However when you send your project to Pypi, I believe only README.rst will be rendered properly. Hence it makes sense to have only README.rst.

Also, again personal preference, put the actual examples to the top to capture the attention. Perhaps before or after the section Advantage and Disadvantage. By the way, it is more natural to say Advantages & Disadvantages (plural). Or perhaps, one word heading:Trade-offs.

**Comment by JacksonWuxs** [comment]
@Dmitrii-I I totally agree with your suggestion about the format of README. In fact, I want to just copy the README.md from Github to README.rst. I have adjusted README again. If you have any other suggestion, please let me know. Anyway, I once again thank you for your help

**Comment by Dmitrii-I** [comment]
Speaking of the devil... From now on PyPI supports markdown: https://dustingram.com/articles/2018/03/16/markdown-descriptions-on-pypi
