### ISSUE TITLE
Please upload the test csv?

### ISSUE THREAD

**Issue by aldanor** [JacksonWuxs/DaPy#3]
Could you upload the test csv used for benchmarking?

**Comment by JacksonWuxs** [comment]
I tried to upload it just now. But it raised an error with '.... file should be less than 25MB....‘
I used 2 test csv which have a large number of records. Therefore, the files  Occupancy 96MB and 240MB.
In fact, I hope you could use your own data set to test Datapy. But if you need my data, please let me know! I will try to e-mail you.

**Comment by JacksonWuxs** [comment]
We have success upload a big data file on [https://pan.baidu.com/s/1kK3_V8XbbVim4urDkKyI8A]. In addition, the last version of DaPy 1.3.2 has been uploaded on Pypi.

**Comment by JacksonWuxs** [comment]
The test code and relevant data has been showed on Readme.md
