### ISSUE TITLE
A new feature for auto-parsing multi-header excel

### ISSUE THREAD

**Issue by renmu123** [JacksonWuxs/DaPy#7]
1. 在 excel 中合并单元格后会导致有一个 header 无法生成，也就拿不到那一列的数据了
![image](https://user-images.githubusercontent.com/26896790/65585532-32734300-dfb5-11e9-851f-8bbf06e7fbc7.png)

2. 在读取 excel 文件的时候，某些 cell.value 过长的时候会导致 `sheet,show()` 显示错位
![image](https://user-images.githubusercontent.com/26896790/65585423-05269500-dfb5-11e9-86d4-dc4084eba21b.png)
[test.xlsx](https://github.com/JacksonWuxs/DaPy/files/3651510/test.xlsx)

**Comment by JacksonWuxs** [comment]
针对问题一：
目前我是使用xlrd做的excel中的读取，他没法很好地区分是否是合并单元格。不知道您有什么建议，可以更好地实现这个功能？

**Comment by JacksonWuxs** [comment]
针对问题二：
sheet.show显示错位的问题主要是中英文的字符长度不同，目前我是在用英文长度计算的，之后我会尝试尽快修复该问题，谢谢您的建议！

**Comment by renmu123** [comment]
> 针对问题一：
> 目前我是使用xlrd做的excel中的读取，他没法很好地区分是否是合并单元格。不知道您有什么建议，可以更好地实现这个功能？

这个处理是没问题的，但是第2列是否不应该是一个空字符串，而是“_1”，第3列才是“_2”

**Comment by JacksonWuxs** [comment]
我在进行自动命名表头的时候，是先进行尽可能保留原始给的字符串。那么在第二列中，由于他给的字符串就是个空字符串，所以我没有进行修改，则第二列的表头为空。再识别第三列的时候，由于发现空字符串命名的列已经存在，所以会在该列的后面自动添加一个_1。在检索到第四列的时候，发现又出现了空字符串，并且_1已经出现过了，所以会自动变为_2。

**Comment by renmu123** [comment]
提一个思路，例如A1-C1是合并单元格，值是A，是否可以将其重命名为A, A_1, A_2。
现在我觉得可能是没有必要的，搞复杂化了

**Comment by JacksonWuxs** [comment]
我的设计思路是这样的，每一列有且仅有一个列标题。我们使用合并单元格的时候一般都会在下一行，会有一个更为细致的列名。比如，合并单元格的内容为“支出”，她底下可能有三个列分别为“食品”、“娱乐”和“生活用品”之类的。所以我的下一步想法是生成："支出_视频”、“支出_娱乐"、”支出_生活用品“这样的列名。
