### ISSUE TITLE
dp.read() 的 first_line 参数好像没有实现

### ISSUE THREAD

**Issue by renmu123** [JacksonWuxs/DaPy#8]

**Comment by JacksonWuxs** [comment]
感谢您的issue，我仔细对该参数进行了检查，确认该参数符合原设计目的，以下是一些关于该参数正常使用的时候需要符合的条件。
1. first_line参数只会在读取csv或txt文件格式的时候有效；
2. first_line参数一定要大于或等于title_line，否则会报错；
3. 设置first_line参数为其他其他值之后，title_line会被修改为first_line - 1.

**Comment by renmu123** [comment]
是不对 xlsx 有支持是吗

我看源代码有写相关的逻辑，以为是还没有实现

        # core.Dataset.py 784
        elif ftype == 'xls' or ftype == 'xlsx':
            first_line = kwrd.get('first_line', 1)
            title_line = kwrd.get('title_line', 0)
            for sheet, name in parse_excel(dtype, addr, first_line, title_line, nan):
                self._add(sheet, name)

**Comment by JacksonWuxs** [comment]
啊，我原来一直记得我只对csv读取的时候实现了这个功能，刚刚发现我对xls也实现了的，但出了点小bug。请你下载最新版的V1.10.10看看能不能实现你的需求。

**Comment by renmu123** [comment]
没问题了
