### ISSUE TITLE
pip 版本Dapy-1.10.10 无法对 Sheet 进行 print

### ISSUE THREAD

**Issue by renmu123** [JacksonWuxs/DaPy#9]
# Dapy.core.base.Sheet.py

在第 863 行有一个 print val，会导致报错无法print

            pattern = [_ for _ in pattern.split(string) if _]
            if len(pattern) == 3:
                val = clear_pattern(pattern[2])
                val = auto_str2value(val)
                print val
                if pattern[1] == symbol:
                    if i == 0:
                        return set(index.unequal(val))
                    return set(func(val))
                try:
                    return set(func(val, False))
                except TypeError:
                    pass
                try:
                    return set(func(val))
                except TypeError:
                    return set()

**Comment by JacksonWuxs** [comment]
啊 这是我调试时候的代码... 我忘记删掉了。 我立刻改

**Comment by JacksonWuxs** [comment]
非常感谢你的许多帮助！

**Comment by JacksonWuxs** [comment]
请下载1.10.11版本。看来我以后发布前，还是得用py3跑一次测试代码的

**Comment by renmu123** [comment]
大家一起促进开源社区的进步(oﾟ▽ﾟ)o
